### ISSUE TITLE
Add inlist controls to set Skye's blend polygon.

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#109]
Skye's EOS blend is specified by giving the vertices of a polygon. These are currently hard-coded in Skye.f90, but it would be good to enable users to set them in inlists.

**Comment by jschwab** [comment]
We don't really have an example of asking the user for a complex boundary.  The existing EOS boundary controls have been pretty much defined as lines, so they usually only require 2 numbers, i.e., the upper/lower limits of some blending region (defined as contours in a quantity, e.g., logQ, logT, logRho).

If the thought is that the user would want to put in some complex polygon, etc., perhaps better to have this option as an `other_skye_region` hook rather than to try and do it through the inlists.

**Comment by adamjermyn** [comment]
Ok. @evbauer is the user most likely to want to do such a thing, so maybe we can hold off on this (but remember it as an option) until he says he wants it...

**Comment by adamjermyn** [comment]
Closing until @evbauer decides to reopen (or someone else).
