### ISSUE TITLE
HELM determines negative abar.

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#276]
In `eos/private/helm.f90` we sometimes get an FPE because the following lines set `abar` to something less than zero:
```
         if (skip_elec_pos) then
            abar = 1d0 / (1/abar - Xfrac/2)
            zbar = 1d-10 ! don't set it to 0
            ytot1 = 1.0d0/abar
            ye    = ytot1 * zbar
         end if
```

This might be perfectly valid logic but I have no idea what it's doing. There may also be something malformed in the HELM request, because the offending cases I've seen (in `dev_to_cc_12` and `dev_to_cc_20`) use `Xfrac=1` and `abar ~ 36`, which seems impossible?

**Comment by jschwab** [comment]
I believe it is trying to pretend things are fully neutral, including molecular H2. (I think that's why the `Xfrac/2` exists.)

I agree having `Xfrac=1` and `abar ~ 36` makes no sense, so that's concerning.

**Comment by adamjermyn** [comment]
I have no idea!

I'd like to suggest that we simplify HELM to just use electrons and positrons and not try these tricks. If we care about partially ionized stuff we shouldn't be using HELM (that's why we have other EOS's)...

**Comment by jschwab** [comment]
Cleaning up / simplifying HELM sounds good to me.  (Most of those crufty things never have actually worked correctly in my experience.)

I believe they exist because we were going off the OPAL tables at the lowRho/T edge and wanted some backstop EOS that wasn't wildly different.  That may be completely unnecessary now because of the wider coverage from FreeEOS.

**Comment by jschwab** [comment]
This code was removed in #283 so the bug is moot.
