### ISSUE TITLE
Determine if (any) parameters should not have defaults

### ISSUE THREAD

**Issue by rjfarmer** [MESAHub/mesa#345]
Some options, are perhaps, important enough choices that the user should be forced to choose instead of using a default. Apparently we made a list in the past but no one can remember where the list is. 

So this is a new list.

For parameters to end up on this list, we need to make sure its well documented what are the possible choices, when you might want a different choice, what to look for if you make a bad choice etc.

- @annethoul wants the convective boundary choice
- ~~I would suggest mixing_length_alpha~~ I retract my suggestion after rereading the old thread on this.

Others?

**Comment by fxt44** [comment]
without defaults for all parameters, mesa will not work out of the box. users, especially less experiences users, will need to make decisions on things they likely do not know. its not clear to me that this is a good path forward.

**Comment by rjfarmer** [comment]
That's also something to consider.

We do have a number of parameters that default to 0, the question is should some more parameters should default to a null/0 value.

**Comment by mjoyceGR** [comment]
I can provide some "standard" MLT values from other codes and explain what
this parametet means, for use in documentation or elsewhere

**Comment by warrickball** [comment]
A middle ground between "working out of the box" and "forcing the user to choose" might be to have a default that triggers an error but all the examples (and particularly the default `work` folder) choosing a value. Hopefully, that it then appears in the user's default inlist makes them aware that an important choice is being made. 

We already do this in some places. e.g. `Zbase`. In `kap/defaults/kap.defaults`, there's
```
    Zbase = -1
```
which would trigger an error, but then the default work folder has
```
    Zbase = 0.02
```
@annethoul's list (or one of them, anyway) is attached to [this message](https://lists.mesastar.org/mailman/private/mesa-developers/2019-December/010157.html) in a meandering thread on the `mesa-devs` mailing list, part of which starts about [here](https://lists.mesastar.org/mailman/private/mesa-developers/2019-December/010122.html). I leave it to @annethoul if she wants to copy her list here (or would like me to). 

Before we all just rehash the same arguments (as I have just done!), we should probably re-read that thread so that we stand a chance at progressing since the last time we discussed this.
