### ISSUE TITLE
1M_thermohaline fails with TDC

### ISSUE THREAD

**Issue by adamjermyn** [MESAHub/mesa#377]
`1M_thermohaline` fails with TDC as of commit `91aecec`.

This is surprising because:
1. It passes with Cox.
2. The time-steps are 100kyr+, which should be long enough that TDC and Cox agree to near machine precision.

There are some thermohaline errors at the beginning of a run with TDC, but @evbauer tells me this shouldn't be an issue.

The various rotational mixing processes seem to give very different answers when TDC is on versus off. I'm not sure if that's the cause or effect here. In any case, this seems to make life difficult for the solver trailing the burning layer in the core, so the timestep gets pushed down when TDC is on.

One thought I had is that  thermohaline and semiconvection both set non-zero convection speeds. TDC then sees these and thinks “Ah there must have been convection here last step!” and in principle that can change the answer it returns, though I think that’s rather unlikely to cause this given how long the time-steps are compared with the convective decay time…

If this is the cause though it’s not obvious we want to change it. It’s worse for making 1M_thermohaline pass, but it might be more physical…

Anyway that seemed unlikely, so I added some instrumentation to `turb_support.f90` to look for differences:
```
         call set_TDC(&
            conv_vel_start, mixing_length_alpha, s% alpha_TDC_DAMP, s%alpha_TDC_DAMPR, s%alpha_TDC_PtdVdt, s%dt, cgrav, m, report, &
            mixing_type, scale, chiT, chiRho, L, r, P, T, rho, dV, Cp, opacity, &
            scale_height, gradL, grada, conv_vel, D, Y_face, gradT, s%tdc_num_iters(k), ierr)

         call set_MLT("Cox", mixing_length_alpha, s% Henyey_MLT_nu_param, s% Henyey_MLT_y_param, &
                        chiT, chiRho, Cp, grav, Lambda, rho, P, T, opacity, &
                        gradr, grada, gradL, &
                        Gamma2, gradT2, Y_face2, conv_vel2, D2, mixing_type, ierr)

         if (abs(conv_vel%val - conv_vel2%val) > 1d2 .or. abs(Y_face - Y_face2) > 1d-3) then
            write(*,*) 'Diff',k,s%m(k)/Msun,conv_vel%val, conv_vel2%val, 0.5d0*(conv_vel%val - conv_vel2%val)/(conv_vel%val + conv_vel2%val), &
                              Y_face%val, Y_face2%val, 0.5d0*(Y_face%val-Y_face2%val)/(Y_face%val+Y_face2%val)
         end if
```

If you throw this in and recompile what you'll see is that initially there are a bunch of order-unity differences in the innermost 0.001Msun, which appears to be in the process of becoming radiative.

I think I know what's happening there: the scale height isn't P/(rho*g). The `scale_height` that gets passed to `Get_results` in `turb_support` is about 10% less than `P/(rho*g)`. TDC and Cox are only equivalent subject to certain conditions, including thermodynamic consistency and that the scale height is the hydrostatic scale height. So I think the latter is the culprit here. This difference is caused by using `alt_scale_height_flag = .true.`, which we set by default.

After that, there are just small differences (~0.01%) in some near-surface cells. That's caused by `gradr_factor` being a bit different from unity, which causes MLT/Cox to pretend there's a different luminosity (whereas TDC directly uses the luminosity, and so doesn't get fooled by this).

I don't actually care too much about "fixing" 1M_thermohaline, because it looks like it would pass on TDC with maybe 50% more models. But I think this raises some questions about how we want to handle `gradr_factor` and `alt_scale_height` with TDC:
1. Do we want TDC to respect `gradr_factor`? If so we need to pass it a different luminosity to get the same effect (just `L*gradr_factor` will do).
2. Do we want to ensure that TDC matches Cox when `alt_scale_height_flag = .true.` and when this actually becomes relevant (which is typically in cores, because that flag is meant to save us from the exploding scale height near the center)? The fix here would be to do a bunch of math to identify every time the equivalency proof uses `h=P/rho g`. In each such instance we'd want to rewrite the TDC equations to use `h` directly rather than (implicitly) computing it by having factors of `P` and so on lying around.

Thoughts?

**Comment by fxt44** [comment]
>  because it looks like it would pass on TDC with maybe 50% more models.

at your convenience, maybe test this?

option 2 seems like a fair bit of work.

**Comment by adamjermyn** [comment]
Here ya go:
https://testhub.mesastar.org/tdc_on_default/commits/4859ca3
Passes in 2x the number of steps.

**Comment by fxt44** [comment]
thanks! if the cost is not unbearable, retain the increase in the maximum number of timesteps on main? at least until this test case is made more efficient or removed in favor of a unit test on the thermohaline options.

**Comment by adamjermyn** [comment]
Sure, that's fine. Closing for now... feel free to reopen if anyone has thoughts/wants those terms to work in TDC the way they work in Cox...

**Comment by warrickball** [comment]
> Do we want TDC to respect gradr_factor? If so we need to pass it a different luminosity to get the same effect (just L*gradr_factor will do).

I presume this is what I was tagged for and I think I should answer, so here goes.

First, for a bit of context, I use `gradr_factor` in the atmosphere so that the temperature matches what one would get for a given T(τ) relation. The _very_ transparent layers (τ << 1) are presumably radiative, so it won't matter what TDC or Cox give. My "implementation" is a result of refactoring the old `opacity_factor` that was introduced in the distant past to mimic the effect of inhomogeneity in the atmosphere changing the effective opacity.

I think the implementation of convection, be it Cox or TDC, should respect `gradr_factor` though I'm not 100% sure. Convective stability (at least the way MESA or most 1D codes do it) ultimately goes back to the temperature gradient of pure radiation, which in the optically thin-ish (e.g. 0.1 < τ < 1) layers is changed by the fact that photons are starting to be able to escape into the void. `gradr_factor` is what accounts for this.

The `T_tau_gradr` test uses `use_T_tau_gradr_factor` and the temperature structure of the atmosphere is the same with TDC as with Cox to within about 0.1%, but I don't know if that's just because a long timestep is short-circuiting back to Cox.

**Comment by adamjermyn** [comment]
> I presume this is what I was tagged for and I think I should answer, so here goes.
Yep!
> The T_tau_gradr test uses use_T_tau_gradr_factor and the temperature structure of the atmosphere is the same with TDC as with Cox to within about 0.1%, but I don't know if that's just because a long timestep is short-circuiting back to Cox.
The differences I was seeing were at the 0.01% level, so that's consistent. There's no long-timestep short-circuiting anymore.

This is an easy fix, so I'll change TDC to take `gradr` as input rather than `L`. That'll make it pick up `gradr_factor` automatically.

I'll leave this issue open to discuss the scale height question.

**Comment by adamjermyn** [comment]
Hmmm but we apply `alt_scale_height` not just to overshooting but to all
the rest of the MLT calculation (e.g. the mixing length gets set by that).

-Adam

**Comment by warrickball** [comment]
Yeah, and I don't really have a strong feeling for whether that makes sense or needs to be consistent with the overshooting or what. But, at least pragmatically, I would've thought it doesn't matter which scale height gets passed to the rest of MLT, since the temperature gradient is basically adiabatic. In that case I wouldn't worry about hacking TDC to match hacked-Cox. I'm happy with documentation (either around `alt_scale_height` or `mlt_option`?) explaining the effect of TDC not using the `alt_scale_height` option.

**Comment by adamjermyn** [comment]
It does make a difference to the convection speeds though. That's the main thing that's different (if I remember correctly...).

Okay, I'll update the docs.
