### ISSUE TITLE
Since MESA-r15140, the memory MESA used reaches about 5~6 GB, and what consumes so much memory?

### ISSUE THREAD

**Issue by xiaoe475** [MESAHub/mesa#409]
Since MESA-r15140, the memory MESA used reaches about 5~6 GB. For MESA-r12778, only about 1G memory is used.
I wonder what consumes so much memory?

**Comment by warrickball** [comment]
MESA's memory usage is dominated by loading tables of what some call "microphysics" data: terms in the equations whose values we interpolate in large tables of data. This includes the opacities but as far as I know the equation of state (EoS) tables are what take up most of the memory. Various choices related to the EoS tables change from version to version so I'm not surprised to see changes in memory use.

Without your being more specific, it's difficult to comment in detail about which EoS change causes the memory usage you see. Offhand, one change was the addition of the FreeEOS tables.

If you're finding the memory usage is a problem and your models are using the FreeEOS tables, you can try disabling them by adding [`use_FreeEOS = .false.`](https://docs.mesastar.org/en/r15140/eos/defaults.html#use-freeeos) to your `&eos` namelist. You can also try setting [`num_steps_for_garbage_collection`](https://docs.mesastar.org/en/r15140/reference/star_job.html#num-steps-for-garbage-collection) in `&star_job` to something like 1000. That de-allocates all the EoS tables, then re-allocates them, so if any aren't being used any more because your star has evolved past where it needs them, you'll get that RAM back.
