### ISSUE TITLE
”log_mtransfer_rate“ in history.data sometimes contain zero values at the onset of the mass transfer process

### ISSUE THREAD

**Issue by xiaoe475** [MESAHub/mesa#510]
The mass transfer rates ("log_mtransfer_rate") in history.data sometimes contain zero values at the onset of the mass transfer process, which is unphysical for a  low-mass star with stable mass transfer in a binary system. 

It seems that there is a bug when converting mass transfer rate values to its logarithmic value.

![image](https://user-images.githubusercontent.com/70212620/225503327-aea29e33-1582-429f-bf2c-1c965981ebe4.png)

**Comment by matthiasfabry** [comment]
Could you provide the configuration (inlists, mesa version) that reproduces this bug?

**Comment by xiaoe475** [comment]
I used MESA-r22.11.1,  and just made a copy of $MESA_DIR/binary/work to simulate a binary with m1=1Msun, M2=1.4Msun, and Porb=1 day. The inlist files and a plotting python script are in the file "work.zip".

[work.zip](https://github.com/MESAHub/mesa/files/10989787/work.zip)

<img width="1682" alt="截屏2023-03-16 19 01 34" src="https://user-images.githubusercontent.com/70212620/225597635-a821582b-2b1b-4436-8ae2-66538bde203d.png">

This figure shows the "lg_mtransfer_rate" as a function of "model_number". When model_number = 131,  132, 1489 and 1518, "lg_mtransfer_rate" shows zero values (actually, 1e-99).

**Comment by matthiasfabry** [comment]
This happens because of the implementation of `safe_log10` in the `math` module.
in most cases when the mass transfer rate is _very_ low (eg ` b% step_mtransfer_rate == -7e-285), the calculation:
`abs(b% step_mtransfer_rate) / Msun * secyer = 0d0`
end up being 0, and `safe_log10` returns `-99` as expected
However sometimes (eg in the steps mentioned above) `abs(b% step_mtransfer_rate) / Msun * secyer = 1.4e-290`, which is a `IEEE_NON_NORMAL` number and so `safe_log10` returns `1d-99`.

I think we could relax this test of `NORMAL`ness to also allow `DENORMAL`s. 
I think comparing to `1e-99` still works with `DENORMALS`. We would then need to test for `IEEE_IS_FINITE`.

**Comment by warrickball** [comment]
https://github.com/MESAHub/mesa/blob/52fea84ea763f61adc232d2589fbae0b990e1831/math/public/math_lib_crmath.f90#L170-L185

Or just return `-99` instead of `1d-99` in the block that catches the `NORMAL`ness? But I'm also not sure why that's written quite so defensively.

Same applies to `safe_log`.

**Comment by evbauer** [comment]
Yes, it looks to me like the intent should be to return `-99d0` rather than `1d-99` in that block. @rhdtownsend?

**Comment by fxt44** [comment]
i'll urge caution before proceeding here. 1d-99 is also used in safe_sqrt. derivatives of the functions, via dfridr or auto_diff, may also be a concern.

**Comment by matthiasfabry** [comment]
I don't know the original intent of `1d-99`, but from a purely numeric standpoint I'd also refrain from returning `-9.9d1` there, as you'd still want `NAN`s and `INF`s to be caught and return something that 'doesn't look like a log'.
I stand by relaxing to testing for `IEEE_IS_FINITE` rather than `IS_NORMAL`.
Let me make a branch and test the suite on this change.

**Comment by evbauer** [comment]
Good, I'm convinced. Maybe we should check with @rhdtownsend before a final merge, but do you want to go ahead and open a branch to test that?
