### ISSUE TITLE
Inconsistency between kappa_plotter files generated in 15140 and 23.05.1

### ISSUE THREAD

**Issue by aurimontem** [MESAHub/mesa#547]
Hi MESA team, 

I don't know if this is an issue that needs fixing, so feel free to ignore, but it's an issue worth flagging. 

I'm trying to use the (oft-overlooked) kappa plotter module in $MESA_DIR/kap/plotter/ to generate opacity tables (at stellar atmosphere densities and temperatures) for independent use outside of MESA, and I'm noticing inconsistencies between the tables generated by older and newer versions of MESA. 

Here is the inlist_plotter used for both runs:
[inlist_plotter_A09_X60Z02.txt](https://github.com/MESAHub/mesa/files/11638922/inlist_plotter_A09_X60Z02.txt)

Here is a table for X=0.6, Z=0.02 with A09 abundances, generated in the latest public revision. 
![image](https://github.com/MESAHub/mesa/assets/11812433/aefe1ddb-43f0-4f1f-8fab-3467b68ff96a)

This, on the other hand, is the same table generated in 15140:
![image](https://github.com/MESAHub/mesa/assets/11812433/77e11d74-a7b6-44c0-aa7a-a7a45fb8676c)

Here is the relevant difference: 
![image](https://github.com/MESAHub/mesa/assets/11812433/6d28476a-af97-4eea-ba11-7973187288f4)

There have obviously been a number of changes under the hood with both the kap module and also in the eos module, both of which are called by $MESA_DIR/kap/plotter/src/kap_plotter.f90, but I just wanted to bring this to your attention. Notably, the new tables produce nans in some (admittedly pathological) regions where they hadn't previously; I'm more worried about the nans than the behavior in the Here Be Dragons region (high rho low T), as well as the blend at low-ish rho intermediate T.

**Comment by Debraheem** [comment]
Interesting, thanks for sharing this @aurimontem. The kap module hasn't changed a whole lot (outside of the monochromatic kap routines) since r15140. Since you're sampling a fixed composition, my initial impression would be that these changes are coming from differences in the eos module between versions, but I wouldn't put it past kap module level differences. It would be interesting to see what the differences look like if you sample from a single Rosseland mean opacity table mixture (e.g. Z = 0.02, X = 0.50 or X = 0.70 ), so you can rule out any interpolation coming out of the kap module?

![kap_diff](https://github.com/MESAHub/mesa/assets/63124736/134a938f-424c-4cb3-9c1a-bcd822a7d0dc)

Looking at the change log for r21.12.1 I find:

(Could explain differences in the Helm region)
-The HELM table was updated to a new, larger 100 points per decade version. 

(changes to the ideal gas implementation at low T?)
-There is a new backstop EOS (ideal) which analytically models an ideal ion gas with radiation pressure. The purpose of this EOS is to provide coverage over the whole density-temperature plane for times when MESA needs to run to extreme densities or temperatures. No electrons are included in this EOS.

----
As far as the differences seen in the FREE-EOS region, maybe there was a shift in the location of the upper blending region that changed between r15140 and rc23.05.1? 

It would be interesting to see what the differences between r15140 and r21.12.1 or r21.12.1 and rc23.05.1?

**Comment by evbauer** [comment]
Yes, that's my understanding. It's just a reporting issue, so the rest of the thermodynamics should be unaffected, but the free electron density is just misreported on FreeEOS in 15140.

**Comment by evbauer** [comment]
I've added a note about this on the [known bugs](https://docs.mesastar.org/en/release-r23.05.1/known_bugs.html#r15140) page in the documentation.
