### ISSUE TITLE
initial_zfracs ignored when loading pre-built ZAMS models

### ISSUE THREAD

**Issue by BucheleL** [MESAHub/mesa#578]
I saw this in two of the labs for this year's summer school, where the intent was to start using a pre-built ZAMS model, then relax to the correct Z and Y values while also changing the z_fracs to the a09 values. However, the pre-built ZAMS models were built using the gs98 abundances, and the z_fracs are not changed by the relax_Z routine. I think the code is working as intended, but the fact that MESA is ignoring the initial_z_fracs set in the inlist is not communicated to the user. 

I see two different ways of communicating the problem to the user: 
1. Give a warning to the user, similar to what is done when loading in a model with a different initial_z than is specified in the inlist 
2. Force MESA to stop, such as when trying to load a default pre-built model with Z other than 0.02 

I'm willing to implement either change, but am not sure what the preferred behavior is.

**Comment by fxt44** [comment]
for some use cases the difference between the two zfracs may not matter, in which case option 1 seems best as it does not to get in the way of doing a run. other cases where the difference is intended to be relevant might prefer option 2. i agree that either is better than no communication!

**Comment by evbauer** [comment]
I don't think this behavior is inconsistent with the documentation for these controls, though it could certainly be more clear. I think of `initial_zfracs` as a control that is a companion to `set_uniform_initial_composition`, which means it only applies when `create_pre_main_sequence_model = .true.`.

So I think option 1 is the right way to go here, and hopefully a warning should suffice to make users go read the documentation in the defaults files more carefully.

**Comment by Debraheem** [comment]
Does this only effect the "relax_Z" routine when loading from a default ZAMS models, because this could impact the simplex_solar_calibration test_suite, if you didn't create a new pre-ms model.

**Comment by Debraheem** [comment]
I believe 'initial_zfracs' are used either when 'create_pre_main_sequence_model = .true.', or if loading a model file with 'set_uniform_initial_composition = .true.' in &starjob.

If you are loading from a ZAMS model and using the relax_Z routine and you'd like to also change the z_fracs, then you must also set 'set_uniform_initial_composition = .true.', however...

If you are loading a ZAMS model, it doesn't necessarily make sense to change the z_fracs, since a ZAMS model is technically an evolved model (h2, li7, CN burning have likely already happened to some extent before Lnuc > 0.99 Lphot (the generally adopted ZAMS condition), so changing the composition after the fact would re-inject h2, li7, C into the model (which could be explosive if the mass or core temperature are large). Initial_zfracs only make sense in the context of setting the initial composition of a uniform mixture to some solar scaled values; therefore if you are hoping to change the z_fracs of a model, it is suggested that you load a fully convective early pms model or use 'create_pre_main_sequence_model'. So perhaps changing the z_fracs to AGSS09 values in your summer school lab should be omitted entirely?

Nonetheless, I certainly agree that some documentation could be added to the 'relax_Z' or 'set_uniform_initial_composition' to clarify this.

**Comment by evbauer** [comment]
After some discussion with the dev team, it sounds like the path forward here is just to add some more documentation to make sure it's clear that the options for selecting zfracs don't apply when you're loading a model.

Separately, we could consider opening a new issue suggesting adding a new `relax_zfracs` procedure that could be applied to ZAMS models, but as Eb has pointed out, that would likely require some tricky decisions about how to handle h2, li7, and c12.
