### ISSUE TITLE
Can MESA be run on AMD Ryzen CPU ?

### ISSUE THREAD

**Issue by Demon-Laplace** [MESAHub/mesa#590]
I'm preparing to buy a new machine, but I noticed that it just provide Linux (Intel) and Mac OS X (Intel, ARM). So I really want to know whether MESA can be run on AMD CPU such as Ryzen 5000 or 7000 series.

**Comment by matthiasfabry** [comment]
Yes, this will be no problem. Ryzen 5000 and 7000 use the x86 instruction set (plus extensions). I assume (intel) is mentioned because Macs only sell with intel chips. @rhdtownsend Should we update the SDK website to just mention "x86-64" instead of Intel? We might as well be more processor inclusive now AMD has a solid share in the PC space.

**Comment by Demon-Laplace** [comment]
Thank you very much!

**Comment by rhdtownsend** [comment]
I've updated the website accordingly.
