### ISSUE TITLE
Can't find MESA SVN commit history between r10724 and r15140

### ISSUE THREAD

**Issue by VincentVanlaer** [MESAHub/mesa#667]
I could find:
* 1 -> 10724 on https://sourceforge.net/p/mesa/code/HEAD/tree/
* 15140 -> 15197 in this repository

I could not find anything about the commits between 10724 and 15140. Are these lost to time?

As an aside, is there a reason the full history wasn't integrated in this repository? It would make it easier to use tools such as `git blame` or just looking at historical contributions, making those contributors more visible.

**Comment by fxt44** [comment]
perhaps 

https://doi.org/10.5281/zenodo.4745225

will help?

**Comment by warrickball** [comment]
> As an aside, is there a reason the full history wasn't integrated in this repository? It would make it easier to use tools such as git blame or just looking at historical contributions, making those contributors more visible.

We discussed this at some length when we made the transition from SVN to git and in essence voted to make a hard break somewhere (which ended up being r15140). Parts of the issue was MESA's early churn in data files and the potential person-effort in making sure the SVN history was preserved correctly.

**Comment by evbauer** [comment]
In case you're curious, the reason there's a break at 10724 on sourceforge is because the online hosting for the SVN repo moved to a paid assembla account for a while at that point. Sourceforge had become increasingly unreliable, and for a while we had funding to pay for a more reliable hosting service, so development of 10724 - 15197 happened over on assembla and never appeared on sourceforge.

The paid assembla account went away after the github migration, so there's no online host for the full SVN repo anymore, but you can set it up locally by unpacking the complete archive from the Zenodo repository that Frank linked.

The MESA sourceforge page really only exists so that the original website mesa.sourceforge.net can redirect to the current docs page.

**Comment by VincentVanlaer** [comment]
Makes sense, thanks for the explanations!
