### ISSUE TITLE
Feature request: warning banner when viewer is not looking at the most recent version of mesa readthedocs

### ISSUE THREAD

**Issue by mjoyceGR** [MESAHub/mesa#691]
By request at the MESA Down Under Summer School: put in a warning banner at the top of docs.mesastar.org if a viewer is not looking at the most recent version of the documentation

**Comment by pmocz** [comment]
Since we do not use version tags that follow semver as specified by the PEP 440, readthedocs cannot automatically detect the `stable` version to add the version warning banner

I added a new Custom Automation rule in the readthedocs admin panel which should kick in when we release  our next version (and hopefully make banners appear automatically)

Reference: 
https://docs.readthedocs.io/en/stable/guides/automation-rules.html

**Comment by mjoyceGR** [comment]
awesome! is there a way to test this before posting a new release?

**Comment by pmocz** [comment]
Unfortunately readthedocs currently does not provide a way to test this feature. But as soon as we create a new github tag, it should activate

**Comment by BucheleL** [comment]
I can now see a banner on the website! This might be a small detail, but it does point to the latest stable version rather than the latest formal release (i.e. I still get the banner even if I'm looking at docs for r24.03.1).

**Comment by pmocz** [comment]
I noticed that too. We are still sorting out some issues with readthedocs.
We can point to stable, but stable is currently not actually getting tied
to a version release number due to a missing feature (in-development) at
readthedocs. Hopefully, this gets fixed soon.

Personally, I like pointing to latest by default, but I would like to know
how others feel about that (I can see it being an issue if latest contains
unreleased features, but a plus if changes in latest contain fixes that are
relevant to previous versions).

**Comment by pmocz** [comment]
The banner issue is finally fixed by tweaking our tags to follow PEP440 standards
