### ISSUE TITLE
Helium flash when using the Ledoux criterion 

### ISSUE THREAD

**Issue by annethoul** [MESAHub/mesa#80]
Cannot pass helium flash when using the Ledoux criterion. Lots of retries (retry: max residual jumped -- give up in solver), stops due to timestep ( stopping because of problems dt < min_timestep_limit).
This is true for masses around 1 Msun. Other masses not tested. 

This is independent of the algorithm used for the convective boundaries. No problem when using the Schwarzchild criterion provided it is used from the TAMS onwards. This is strange since both criteria should give essentially identical models when using the CPM algorithm!

It is possible to go through helium flash with the Ledoux criterion by using the control 
convergence_ignore_equL_residuals = .true.
This is not convenient for the "one inlist fits all" aficionados.

Version tested: 14356. But note that this is an ancient issue, mentionned in a long mesa-dev thread initiated by me under the subject "Problems for He flash and Ledoux criterion" in July 2018 (version 10881).
I am assigning this to myself but considering my debugging success rate, it might be nice if others look also into it ;-)

**Comment by warrickball** [comment]
I've just been forced back to this problem myself, exactly because I have a 1.5 Msun model that I need to get through the flash *with* Ledoux, and I'm only now digesting the inlist @adamjermyn shared and the animation of the 1.5 Msun star's evolution.

First, in the video, what happens around model 400, around the base of the RGB? The HR track does some loops that I think could be described as "crazy", taking Teff to ~2500 K before continuing.

Second, there's a *lot* going on in that inlist, including thermohaline mixing, hydrodynamics and convective premixing. Do you have any idea which of these are necessary to get through? I've done a run with `delta_lgL_He_limit = 3d-3` in isolation but that didn't get me through the flash. I *have* been using `varcontrol_target = 1d-4` until now but I might relax that to `1d-3` to see what happens. Basically, can we get through without switching on any "extra" physics?

To be honest I'm just non-systematically flipping all the switches and turning all the dials in the inlist and nothing's working. In the absence of progress, I think I'll move to activating `convergence_ignore_equL_residuals` during the flash, and consider re-opening this.

**Comment by adamjermyn** [comment]
Not sure about the first one.

Thermohaline is necessary to match observed Li abundances. These settings run (at least for 1Msun) just fine without it. So feel free to chuck that part.

You can probably get rid of min_D_mix as well. That just prevents mesh refinement from producing garbage in the brunt profile.

I have gotten models to run without hydrodynamics, but don't have an inlist handy. Try it and see!

I'd recommend starting with this inlist exactly as is and methodically removing things one at a time if you'd really like to simplify it. I don't have the interest/time to do that, but if you do I'll be curious what you find!
